@ECHO OFF
SETLOCAL
SET vCF_API_ENDPOINT=%pCF_URL%
SET vCF_USER=%pCF_USER%
IF [%pCF_PASSWORD%] EQU [] (
 ECHO NO PASSWORD
) ELSE (
  SET vCF_PARAMETER_PASSWORD= -p %pCF_PASSWORD%
  ECHO WITH PASSWORD
)
SET vCF_ORG=%pCF_ORG%
SET vCF_SPACE=%pCF_SPACE%

:: run
ECHO Login in %vCF_API_ENDPOINT% - %vCF_ORG% - %vCF_SPACE% with %vCF_USER% 
cf login -u %vCF_USER% %vCF_PARAMETER_PASSWORD% -a %vCF_API_ENDPOINT% -o "%vCF_ORG%" -s "%vCF_SPACE%"
ECHO ##
ECHO Logged
ECHO ##
ENDLOCAL
